import type { Locale } from "./i18n";
import type { PipelineResult } from "./types";

function download(name: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function exportJson(result: PipelineResult) {
  download(`${result.request.title || "prompt-pack"}.json`, JSON.stringify(result, null, 2), "application/json");
}

export function toMarkdown(result: PipelineResult, locale: Locale = "zh-CN") {
  const en = locale === "en-US";
  const labels = en ? {
    identity: "Role", appearance: "Appearance", personality: "Personality", motifs: "Visual motifs",
    source: "Source mapping", shot: "Shot", characters: "Characters", none: "None", location: "Location",
    action: "Action", emotion: "Emotion", composition: "Composition", lighting: "Lighting",
    continuity: "Continuity constraints", post: "Post-production text", narration: "Narration", dialogue: "Dialogue",
    generated: "Generated by Xuge", summary: "Project summary", mode: "Adaptation mode", panels: "Target panels",
    style: "Visual style", themes: "Themes", adaptation: "Adaptation Plan", pacing: "Pacing",
    visual: "Visual strategy", cards: "Prompt Cards", audit: "Audit", score: "Score", suggestion: "Suggestion",
    clear: "No clear issues found", spine: "Narrative Spine", centralQuestion: "Central question", protagonist: "Protagonist",
    goal: "Goal", obstacle: "Obstacle", resolution: "Resolution", causal: "Causal chain", chronology: "Chronology strategy",
    sequences: "Sequence plan", budget: "panels", readerLayer: "Reader-visible layer", timeCard: "Time card",
    locationCard: "Location card", transition: "Transition caption", cause: "Link from previous panel",
    readerLearns: "What the reader learns", coldRead: "Zero-context reader", retelling: "Reader retelling",
    gaps: "Unclear or missing links", passed: "Passed", failed: "Failed", autoRevision: "Automatic clarity revision applied"
  } : {
    identity: "身份", appearance: "外观", personality: "性格", motifs: "视觉母题",
    source: "原文映射", shot: "镜头", characters: "人物", none: "无", location: "地点",
    action: "动作", emotion: "情绪", composition: "构图", lighting: "光线",
    continuity: "连续性约束", post: "后期文字", narration: "旁白", dialogue: "对白",
    generated: "由叙格生成", summary: "项目摘要", mode: "改编模式", panels: "目标格数",
    style: "视觉风格", themes: "主题", adaptation: "改编方案", pacing: "节奏",
    visual: "视觉策略", cards: "Prompt Cards", audit: "审核", score: "总分", suggestion: "建议",
    clear: "未发现明确问题", spine: "叙事主干 Narrative Spine", centralQuestion: "核心问题", protagonist: "主角",
    goal: "目标", obstacle: "阻碍", resolution: "结果", causal: "因果链", chronology: "时间线策略",
    sequences: "场景段落与格数分配", budget: "格", readerLayer: "读者可见层", timeCard: "时间卡",
    locationCard: "地点卡", transition: "转场字幕", cause: "承接上一格", readerLearns: "本格新增信息",
    coldRead: "零背景读者", retelling: "读者复述", gaps: "不清楚或缺失的连接", passed: "通过", failed: "未通过",
    autoRevision: "已自动执行清晰度修订"
  };
  const listSeparator = en ? ", " : "、";
  const detailSeparator = en ? "; " : "；";
  const characters = result.storyBible.characters.map((character) =>
    `### ${character.name}\n\n- ${labels.identity}: ${character.role}\n- ${labels.appearance}: ${character.appearance.join(detailSeparator)}\n- ${labels.personality}: ${character.personality.join(detailSeparator)}\n- ${labels.motifs}: ${character.visualMotifs.join(detailSeparator)}`
  ).join("\n\n");

  const panels = result.panels.map((panel) => `## ${String(panel.order).padStart(2, "0")} · ${panel.sequenceTitle} · ${panel.storyPurpose}

**${labels.source}**: ${panel.sourceExcerpt}

**${labels.readerLayer}**

- ${labels.timeCard}: ${panel.timeCard || labels.none}
- ${labels.locationCard}: ${panel.locationCard || labels.none}
- ${labels.transition}: ${panel.transitionCaption || labels.none}
- ${labels.narration}: ${panel.narration || labels.none}
- ${labels.dialogue}: ${panel.dialogue || labels.none}

**${labels.cause}**: ${panel.causeFromPrevious || labels.none}

**${labels.readerLearns}**: ${panel.readerLearns}

- **${labels.shot}**: ${panel.shotSize} / ${panel.cameraAngle}
- **${labels.characters}**: ${panel.characters.join(listSeparator) || labels.none}
- **${labels.location}**: ${panel.location}
- **${labels.action}**: ${panel.action}
- **${labels.emotion}**: ${panel.emotion}
- **${labels.composition}**: ${panel.composition}
- **${labels.lighting}**: ${panel.lighting}

**Prompt**

${panel.prompt}

**Negative Prompt**

${panel.negativePrompt}

**${labels.continuity}**

${panel.continuity.map((item) => `- ${item}`).join("\n")}
`).join("\n---\n\n");

  const spine = result.adaptation.narrativeSpine;
  const sequencePlan = result.adaptation.sequences.map((sequence) =>
    `- **${sequence.title}** · ${sequence.panelBudget} ${labels.budget}: ${sequence.purpose} (${[sequence.time, sequence.location, sequence.transitionIn].filter(Boolean).join(" · ")})`
  ).join("\n");
  const gaps = [...result.audit.coldRead.missingLinks, ...result.audit.coldRead.unclearPoints];

  return `# ${result.request.title}\n\n> ${labels.generated} · ${new Date(result.createdAt).toLocaleString(locale)} · ${result.provider}\n\n## ${labels.summary}\n\n${result.storyBible.logline}\n\n- ${labels.mode}: ${result.request.mode}\n- ${labels.panels}: ${result.request.panelCount}\n- ${labels.style}: ${result.request.style}\n- ${labels.themes}: ${result.storyBible.themes.join(listSeparator)}\n\n# Story Bible\n\n${characters}\n\n# ${labels.adaptation}\n\n${result.adaptation.approach}\n\n**${labels.pacing}**: ${result.adaptation.pacing}\n\n**${labels.visual}**: ${result.adaptation.visualStrategy}\n\n## ${labels.spine}\n\n- ${labels.centralQuestion}: ${spine.centralQuestion}\n- ${labels.protagonist}: ${spine.protagonist}\n- ${labels.goal}: ${spine.goal}\n- ${labels.obstacle}: ${spine.obstacle}\n- ${labels.resolution}: ${spine.resolution}\n\n**${labels.causal}**\n\n${spine.causalChain.map((item, index) => `${index + 1}. ${item}`).join("\n")}\n\n**${labels.chronology}**: ${result.adaptation.chronologyStrategy}\n\n**${labels.sequences}**\n\n${sequencePlan}\n\n# ${labels.cards}\n\n${panels}\n\n# ${labels.audit}\n\n${labels.score}: ${result.audit.score}/100\n\n${result.audit.summary}\n\n## ${labels.coldRead} · ${result.audit.coldRead.passed ? labels.passed : labels.failed} (${result.audit.coldRead.score}/100)\n\n**${labels.retelling}**: ${result.audit.coldRead.retelling || labels.none}\n\n**${labels.gaps}**: ${gaps.join(detailSeparator) || labels.none}\n\n${result.audit.autoRevisionApplied ? `> ${labels.autoRevision}\n\n` : ""}${result.audit.issues.map((issue) => `- **${issue.severity} ${issue.target}**: ${issue.message} ${labels.suggestion}: ${issue.suggestion}`).join("\n") || `- ${labels.clear}`}\n`;
}

export function exportMarkdown(result: PipelineResult, locale: Locale = "zh-CN") {
  download(`${result.request.title || "prompt-pack"}.md`, toMarkdown(result, locale), "text/markdown;charset=utf-8");
}
